### ISSUE TITLE
Can't extract source image from jpg made with DEPTHY.ME

### ISSUE THREAD

**Issue by seene-club** [vanitasvitae/DepthMapNeedle#1]
Hi vanitasvitae, 
I made a blurred image with DEPTHY.ME.
I used DepthMapNeedle to extract the depthmap PNG. This works great!
But I have a problem when I try to extract the source image.

JPEGUtils getEXIFBlock: No EXIF-block found
JPEGUtils extract found start for "GImage:Data": false
JPEGUtils extractSourceImage is null
Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException
	at org.vanitasvitae.depthmapneedle.ArrayUtils.unsign(ArrayUtils.java:97)
	at org.vanitasvitae.depthmapneedle.JPEG.exportSourceImage(JPEG.java:151)
	at org.vanitasvitae.depthmapneedle.JPEG.exportSourceImage(JPEG.java:140)

Is the format from DEPTHY.ME not correct?
I attached the xmp jpg.
Thanks for helping me out here.

![poster_xmp](https://cloud.githubusercontent.com/assets/11654139/8723308/fa0593ce-2bcc-11e5-9f6e-957338fc89a3.jpg)

**Comment by vanitasvitae** [comment]
Hi!
Thanks for your report. Unfortunately Im busy right now, so I cant answer in too much detail, but it seems that either DEPTHY.ME doesnt store the unblurred image in the jpg file at all or under an other data section. The Google camera app stores the source image like "GImage:Data=<Image>". This section seems to be missing in your posted picture. 
I will later look, if I can find something about this.
Vanitas

**Comment by vanitasvitae** [comment]
Depthy.Me does not include a source image into the file. Instead the Image itself is the source file, so there is no need to export it via DepthMapNeedle. I hope this answers your question :)
PS: I also added recognition for the image type of the depthmap. Now you dont have to rename the output depthmap.png to depthmap.jpg anymore ;P

**Comment by seene-club** [comment]
Thank you very much! Great project!
